apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVaultSecretProviderName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    clientID: {{ .Values.managedIdentityClientId }}
    keyvaultName: {{ .Values.keyVaultName }}
    tenantID: {{ .Values.tenantId }}
    objects:  |
      array:
        - |
          objectName: {{ .Values.keyVaultStorageAccountConnectionStringSecretName }}
          objectType: secret