apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.managedIdentityClientId }}
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}